language: java
sudo: false
script: mvn clean verify package
deploy:
  provider: heroku
  api_key:
    secure: pqVqHabxPzUp4dttX8sxIYaf9VAFBrms42UuTyx3b9YFYHQ6oVYHqYqDlFPFVWTsQ12S5k4duCoPtdlwuFjqzZz3HqKhtQxVrjvQkeVfd9mYTBwxwlxQIcNkUQOM4r1JylQej05gY981OQCzOBbCRH7prGRNtdAHww5Zmtpil0ADOaL4RfZe5v0k6dKLlLw4jksSvqllbRUSHCm7yE58NJogqhLimz6aDBryz0XRHiN3dIzN4Y9XRv2PkH3cwuSl+BVkltwgAAN9HJrHsodMe0u0WbWCISuUw9R5ZETEXg7RDSCJgpE2wzsDZ5Fu+iP7Hx4AquluUi72/HQFVUWKkyR7wut0fAYJaPFJ3IapbbR+/AaNMpLDG+3r0k0nMQORGJVErSs6hG2weA7C5vxGMaRIOxvH3EdZey+E0pcQ0etRfQA5yJCW39OPynYzDwVHX6PqvebQbfk93JXT5mkLYEU7uj3CwSPpbUuzm2EtJ2AKeQJpZBVkGIsv3YL+k2AWaEVgT56pBmT1UqUlT42XrAcVUp8ko7KdFw+PHWG6nZ2volWY57dESEdNIbyDxhMl8vQ36V5gcHJabuVjCWU6s1jP86rmjpJfbtTiuWBpi2cVH1M+DCOPhImlC3QIaIltshrogyItFnEhxE0sLKPu8idk/Cb3CL4dJFJY5VMqbX8=
  app: mighty-lake-78410
  on:
    repo: WeberCS4230/Twitter-Thing
