language: java
jdk:
  - oraclejdk8
sudo: false
script: mvn clean verify package
deploy:
  provider: heroku
  api_key:
    secure: oWyNR5DfCy36fxVf7GsJUzdENM+5l6KouajOwJ9GbGdtk5UsvTeiD6d7wa5y0fy/ELyxgEPCuKjjAWvoBRoNqCM3yFpvZigIrVEl41SwvGHw8CT5mElFC/X7gw6E8kPZpA/pXiAe/UZOY6MPXaFJFIpBk+uhdX1+c/HTLbwYa9+Ttvqe0fyNiTnKxT7JK0Bsofh0/sunGCpnKsNgWcfeSdtbl8TzEsi26cXSyvXWbB4xAhRwwetDXV+oiq24UJwSA9K7jK+Lh4z8O1xPJpbw4/k6xiv8x41sv2odPIFDjLaSUBDBiV0moBvmt6/eaxBQt+9ifS+TQCPn1iq8Nc3WpbegLBctaOZTTGi2Y8+x0WCnQWqGG8EmGAqIsXoMP6MBUW95lXR+4piTBCuZHgZVQubOUeZ14EkZynx77kQ7jRzf2R1qRzuI4zLKKd8K2aWext6jLYwQkJA3HG+fyFxzivUn4Dao9TorxZipuuSJx3pV6vaCOxxuWzX6T99qXQ2Y8yMVdfeFeKGiweAn0p7FRKkJCIj0ZLoQm9r9Rw6qFg1TJn2E21L3phUsmSMd4B6s0ZD8WKXS4yw//aqYYIJShEKduFXGYD3lky6wUYT4pD8y+LoM23R0Z8Epc3a46NSinSfYf1HpXg1LA1S+AgTJ2fiDq2EgkaiFfGuXY77jEdk=
  app: cs4230-twitter-thing
  on:
    repo: WeberCS4230/Twitter-Thing
cache:
  directories:
    - '$HOME/.m2/repository'